[parity]
chain = "parity_spec.json"

[account]
unlock = ["0x009A2B631BD26B782fC47Bbc373A4fCE26E81048"]
password = ["Chainsafe"]


[mining]
engine_signer = "0x009A2B631BD26B782fC47Bbc373A4fCE26E81048"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0
