keystore = "keys"
estimated_gas_cost_of_withdraw = 0

[home]
account = "0x00bd138abd70e2f00903268f3db08f2d25677c9e"
required_confirmations = 0
rpc_host = "http://127.0.0.1"
rpc_port = 8550
password = "password.txt"
default_gas_price = 0

[home.contract]
bin = "../compiled_contracts/HomeBridge.bin"

[foreign]
account = "0x00bd138abd70e2f00903268f3db08f2d25677c9e"
required_confirmations = 0
rpc_host = "http://127.0.0.1"
rpc_port = 8551
password = "password.txt"
default_gas_price = 0

[foreign.contract]
bin = "../compiled_contracts/ForeignBridge.bin"

[authorities]
accounts = [
	"0x00bd138abd70e2f00903268f3db08f2d25677c9e",
	"0x00a329c0648769a73afac7f9381e08fb43dbea72"
]
required_signatures = 1

[transactions]
home_deploy = { gas = 3000000 }
foreign_deploy = { gas = 3000000 }
#deposit_relay = { gas = 3000000 }
#withdraw_relay = { gas = 3000000 }
#withdraw_confirm = { gas = 3000000 }
